### PR TITLE
API v2 library

### PR DESCRIPTION
**Pull request by meliaj**

### CODE REVIEW

**Comment by beenakamath** [comment]
Most of this seems auto-generated code -- except the overrides. Is there any documentation on how to determine what needs to be over-ridden somewhere?

**Comment by meliaj** [comment]
The override script in override/override.sh is some documentation. Does that help?

In general we need to override events to be polymorphic which differs in what needs to be done by client library and language.

And I like to rename things from "swagger" to "Clever" and tidy up the README.

**Comment by meliaj** [comment]
There is also a test that events actually are unmarshalled properly

**Comment by beenakamath** [comment]
Thanks, I just wanted to make sure there's enough documentation for some one new to this to be able to do this for future versions.

**Review by beenakamath — APPROVED** [review]

**Comment by meliaj** [comment]
Regenerated with small change to have normalized Contact phone type

**Review by beenakamath — APPROVED** [review]

**Pull request merged**
